name: "Custom Deploy In Kubernates"
description: "Deploy to Dev Cluster"
inputs:
  repo:
    description: "Repository name"
    required: true
  branch:
    description: "Branch name"
    required: true
  commit-hash:
    description: "Commit hash"
    required: true
  private-key:
    description: "Ssh private key"
    required: true
  git-username:
    description: "Git username"
    required: true
  git-email:
    description: "Git e-mail"
    required: true
  fleet-repo:
    description: "Fleet repo"
    required: true
  fleet-path:
    description: "Fleet path"
    required: true
  fleet-values-path:
    description: "Fleet values.yaml path"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set Repo Name
      id: set-repo-name
      run: |
        REPO_NAME=${{ inputs.repo }}
        REPO_NAME=$(echo $REPO_NAME | tr '[:upper:]' '[:lower:]')
        echo "::set-output name=repo-name::$REPO_NAME"
      shell: bash

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.private-key }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts
      shell: bash

    - name: Setup Git Config
      run: |
        git config --global user.name "${{ inputs.git-username }}"
        git config --global user.email "${{ inputs.git-email }}"
      shell: bash

    - name: Clone Repository And Update
      run: |
        git clone -b ${{ inputs.branch }} ${{ inputs.fleet-repo}}
        cd ${{ inputs.fleet-path}}
        sed -i "/${{ steps.set-repo-name.outputs.repo-name }}:/ { n; s/.*/  imageTag: \"${{ inputs.commit-hash }}\"/; }" ${{ inputs.fleet-values-path}}
        git add .
        git commit -m "Update ${{ steps.set-repo-name.outputs.repo-name }} version to ${{ inputs.commit-hash }}"
        git push origin ${{ inputs.branch }}
      shell: bash
