name: Release on Any Branch Push
on: push

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Extract commit hash
        shell: bash
        run: echo "##[set-output name=hash;]$(echo ${GITHUB_SHA::6})"
        id: extract_hash

      # - name: Build Project
      #   run: # Your build commands here

      # - name: Run Tests
      #   run: # Your test commands here

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_branch.outputs.branch }}-${{ steps.extract_hash.outputs.hash }}
          release_name: Release ${{ steps.extract_branch.outputs.branch }}-${{ steps.extract_hash.outputs.hash }}
          draft: false
          prerelease: false
